### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by fuyutsuki** [itsu020402/MusicPlayer#1]
> 00:26:16 [ALERT] [MusicPlayer] エラーが発生しました。
00:26:16 [INFO] [MusicPlayer] 音楽の読み込みが完了しました。
00:26:16 [ALERT] java.lang.RuntimeException: java.lang.NoClassDefFoundError: cn/nukkit/window/FormWindow
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:633)
        at cn.nukkit.Server.enablePlugins(Server.java:622)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.NoClassDefFoundError: cn/nukkit/window/FormWindow
        at itsu.mcpe.musicplayer.MusicPlayer.onEnable(MusicPlayer.java:41)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: cn.nukkit.window.FormWindow
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more
00:26:16 [INFO] MusicPlayer v1.1.0を無効にしています…

jarはビルド済みのものをダウンロードしました。
サーバーソースは NukkitX です。

**Comment by fuyutsuki** [comment]
すみません、NukkitXとNukkitでのAPIの互換性がないために発生する問題ですね。。。

**Comment by fuyutsuki** [comment]
どの最新のサーバーソースでもこの問題が発生したためreopen

**Comment by nao20010128nao** [comment]
https://github.com/NukkitX/Nukkit/blob/master/src/main/java/cn/nukkit/form/window/FormWindow.java    
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/form/window/FormWindow.java    
`Lcn/nukkit/form/window/FormWindow;`はNukkitにもNukkitXにもあるのでただ単にバージョンが古いだけでは?

**Comment by fuyutsuki** [comment]
やり直してみます

**Comment by itsu020402** [comment]
cn.nukkit.window.FormWindowを使っているのはJupiterだけだと思います...

**Comment by Megapix96** [comment]
Formに関しては
Nukkit=NukkitX=CoreX=MCConCN≠Jupiter
となっております

**Comment by itsu020402** [comment]
互換させます？？

**Comment by Megapix96** [comment]
うーん
